services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DFT_POSTGRES_DB:-dftools}
      POSTGRES_USER: ${DFT_POSTGRES_USER:-dfuser}
      POSTGRES_PASSWORD: ${DFT_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  dftools:
    init: true
    build: .
    ports:
      - ${DFT_PORT:-3000}:${DFT_PORT:-3000}
    depends_on:
      - postgres
      - redis
    environment:
      PORT: ${DFT_PORT:-3000}
      DATABASE_URL: postgres://${DFT_POSTGRES_USER:-dfuser}:${DFT_POSTGRES_PASSWORD}@postgres:5432/${DFT_POSTGRES_DB:-dftools}
      REDIS_URL: redis://redis:6379/0
      DOMAIN: ${DFT_DOMAIN}
      JWT_KEY: ${DFT_JWT_KEY}
      SECRET_KEY: ${DFT_SECRET_KEY}
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

